name: Print Branch Name on Pull Request

on:
    pull_request:
        branches:
            - "*"

jobs:
    print-branch-name:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Print source branch name
              run: |
                  echo "Source branch: ${{ github.head_ref }}"
              shell: bash
