services:
  audit_logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audit_logger
    environment:
      - SERVICE_NAME=audit-logger
      - ENVIRONMENT=qa
      - LOG_LEVEL=warn
      - PORT=3003
    ports:
      - "3003:3003"

  report_engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: report_engine
    environment:
      - SERVICE_NAME=report-engine
      - ENVIRONMENT=dev
      - LOG_LEVEL=error
      - PORT=3004
    ports:
      - "3004:3004"
