services:

  mysql84:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  mysql8:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
